-- ============================================================================
-- Avinerpedia database schema
-- Reconstructed from lib/types.ts, lib/db.ts, app/**, scripts/import-from-wiki.ts
-- and scripts/setup-categories-db.sql / add-is-active-column.sql.
--
-- Run once in the Supabase SQL Editor on an empty `public` schema.
-- Then:  npx tsx scripts/import-from-wiki.ts
-- Then:  select public.sync_content_categories();
-- ============================================================================

create extension if not exists pg_trgm with schema extensions;

-- ----------------------------------------------------------------------------
-- categories: main categories (סדרות, שו"ת הלכה, מאמרים, סרטונים) and their
-- sub-categories. Integer ids, as lib/types.ts `Category` expects.
-- ----------------------------------------------------------------------------
create table public.categories (
  id            serial primary key,
  name          text not null,
  type          text not null check (type in ('main', 'sub')),
  parent_id     integer references public.categories (id) on delete set null,
  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  unique nulls not distinct (name, type, parent_id)
);

create index idx_categories_parent_id on public.categories (parent_id);
create index idx_categories_type      on public.categories (type);

insert into public.categories (name, type, display_order) values
  ('סדרות',     'main', 10),
  ('שו"ת הלכה', 'main', 20),
  ('מאמרים',    'main', 30),
  ('סרטונים',   'main', 40);

-- ----------------------------------------------------------------------------
-- content_items: every lesson / article / Q&A / series episode.
-- main_category / sub_category are the legacy text columns the pages filter on;
-- *_category_id are the normalized links kept in sync by the admin code.
-- ----------------------------------------------------------------------------
create table public.content_items (
  id               bigint generated by default as identity primary key,
  original_id      integer,
  title            text not null unique,          -- import-from-wiki upserts on title
  main_category    text not null,                 -- no CHECK: /french uses 'Cours en Français'
  sub_category     text,
  main_category_id integer references public.categories (id) on delete set null,
  sub_category_id  integer references public.categories (id) on delete set null,
  video_id         text,                          -- YouTube id or 'Maale:<id>'
  publish_date     date,
  summary          text,
  original_tags    text,
  content_md       text,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  fts              tsvector generated always as (
                     setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                     setweight(to_tsvector('simple', coalesce(summary, '')), 'B') ||
                     setweight(to_tsvector('simple', coalesce(content_md, '')), 'C')
                   ) stored
);

create index idx_content_items_main_category    on public.content_items (main_category);
create index idx_content_items_sub_category     on public.content_items (sub_category);
create index idx_content_items_main_cat_id      on public.content_items (main_category_id);
create index idx_content_items_sub_cat_id       on public.content_items (sub_category_id);
create index idx_content_items_is_active        on public.content_items (is_active);
create index idx_content_items_created_at       on public.content_items (created_at desc);
create index idx_content_items_has_video        on public.content_items (created_at desc)
  where video_id is not null and video_id <> '';
create index idx_content_items_fts              on public.content_items using gin (fts);
-- Speeds up the `title.ilike.%q%` searches in lib/db.ts and app/api/search.
create index idx_content_items_title_trgm       on public.content_items using gin (title extensions.gin_trgm_ops);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger content_items_touch_updated_at
  before update on public.content_items
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- admin_users: who may use /admin (app/admin/login, app/api/admin/*).
-- ----------------------------------------------------------------------------
create table public.admin_users (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null unique references auth.users (id) on delete cascade,
  role       text not null default 'editor' check (role in ('admin', 'editor')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

-- ----------------------------------------------------------------------------
-- Row Level Security: everyone can read content; only admins can write.
-- (The service role key used by scripts/ bypasses RLS.)
-- ----------------------------------------------------------------------------
alter table public.categories    enable row level security;
alter table public.content_items enable row level security;
alter table public.admin_users   enable row level security;

create policy "categories: public read"  on public.categories    for select using (true);
create policy "categories: admin write"  on public.categories    for all
  using (public.is_admin()) with check (public.is_admin());

create policy "content: public read"     on public.content_items for select using (true);
create policy "content: admin write"     on public.content_items for all
  using (public.is_admin()) with check (public.is_admin());

create policy "admin_users: read own row" on public.admin_users  for select
  using (user_id = auth.uid());

-- ----------------------------------------------------------------------------
-- Run after each import: builds sub-categories from content_items, links the
-- *_category_id columns, and deactivates items with neither text nor video
-- (same logic as scripts/setup-categories-db.sql + add-is-active-column.sql).
-- ----------------------------------------------------------------------------
create or replace function public.sync_content_categories()
returns table (main_linked bigint, sub_categories bigint, sub_linked bigint, deactivated bigint)
language plpgsql security definer set search_path = public as $$
declare
  v_main bigint; v_subcats bigint; v_sub bigint; v_inactive bigint;
begin
  update content_items ci set main_category_id = c.id
  from categories c
  where c.type = 'main' and c.name = ci.main_category
    and ci.main_category_id is distinct from c.id;
  get diagnostics v_main = row_count;

  -- Each sub-category goes under the main category most of its items belong to.
  insert into categories (name, type, parent_id)
  select distinct on (ci.sub_category) ci.sub_category, 'sub', ci.main_category_id
  from content_items ci
  where ci.sub_category is not null and ci.sub_category <> '' and ci.main_category_id is not null
    and not exists (select 1 from categories c where c.type = 'sub' and c.name = ci.sub_category)
  group by ci.sub_category, ci.main_category_id
  order by ci.sub_category, count(*) desc
  on conflict do nothing;

  select count(*) into v_subcats from categories where type = 'sub';

  update content_items ci set sub_category_id = c.id
  from categories c
  where c.type = 'sub' and c.name = ci.sub_category
    and ci.sub_category_id is distinct from c.id;
  get diagnostics v_sub = row_count;

  update content_items set is_active = false
  where is_active
    and coalesce(content_md, '') = ''
    and coalesce(video_id, '') = '';
  get diagnostics v_inactive = row_count;

  return query select v_main, v_subcats, v_sub, v_inactive;
end;
$$;

revoke execute on function public.sync_content_categories() from public, anon, authenticated;
