/**
 * Legacy MediaWiki URLs (shlomo-aviner.net) -> new site paths.
 *
 * The mapping in lib/legacy-redirects.json is generated by
 * scripts/source/build-legacy-redirects.ts from the wiki's XML export and Supabase;
 * app/[...legacy]/route.ts serves the redirects.
 */

import redirects from './legacy-redirects.json';
import { legacyTitleKey, safeDecode } from './legacy-title';

export interface LegacyRedirects {
  /** normalized title (incl. "קטגוריה:X") -> new path, served as 301 */
  titles: Record<string, string>;
  /** MediaWiki page id (curid) -> new path, served as 301 */
  curids: Record<string, string>;
  /** normalized title -> search query, for redirects whose target page no longer exists (302) */
  searches: Record<string, string>;
}

export type LegacyResolution =
  | { status: 301; location: string }
  | { status: 302; location: string }
  | { status: 404 };

const map = redirects as LegacyRedirects;
const searchPath = (q: string) => (q ? `/library?q=${encodeURIComponent(q)}` : '/');

/**
 * Resolves a legacy request. `pathname` is the raw (possibly percent-encoded) path;
 * `params` are its query parameters.
 */
export function resolveLegacy(pathname: string, params: URLSearchParams): LegacyResolution {
  const path = safeDecode(pathname).replace(/^\/+/, '');

  // /index.php?title=X, /index.php?curid=N (also under the wiki's /w/ script path)
  if (/^(w\/)?index\.php$/i.test(path)) {
    const curid = params.get('curid') || params.get('page_id');
    if (curid && map.curids[curid]) return { status: 301, location: map.curids[curid] };
    const title = params.get('title');
    return title ? byTitle(title) : { status: 301, location: '/' };
  }

  // Asset-like paths (favicon.ico, *.png, wp-login.php...) and the app's own namespaces
  // (unknown /api/..., /admin/..., /_next/... paths) are not wiki pages.
  if (/\.[a-z0-9]{2,4}$/i.test(path) || /^(api|admin|_next)(\/|$)/i.test(path)) return { status: 404 };

  // /Title_With_Underscores (titles may contain "/", so the whole path is the title)
  return byTitle(path);
}

/** `title` is already decoded (from the decoded path or from URLSearchParams). */
function byTitle(title: string): LegacyResolution {
  const key = legacyTitleKey(title);
  if (!key) return { status: 301, location: '/' };
  const target = map.titles[key];
  if (target) return { status: 301, location: target };
  const query = map.searches[key] ?? key.replace(/^קטגוריה:/, '');
  return { status: 302, location: searchPath(query) };
}
